version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered pre-build stage."

  build:
    commands:
    - echo "Entered build stage."
    - mvn clean install -DskipTests

  post_build:
    commands:
    - echo "Entered post-build stage."

artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'